-- MySQL Script generated by MySQL Workbench
-- Wed Jun 20 08:38:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb1` ;

-- -----------------------------------------------------
-- Schema mydb1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb1` DEFAULT CHARACTER SET utf8 ;
USE `mydb1` ;

-- -----------------------------------------------------
-- Table `mydb1`.`Departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb1`.`Departments` ;

CREATE TABLE IF NOT EXISTS `mydb1`.`Departments` (
  `idDepartments` INT NOT NULL AUTO_INCREMENT,
  `DepartmentsName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDepartments`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb1`.`Employ`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb1`.`Employ` ;

CREATE TABLE IF NOT EXISTS `mydb1`.`Employ` (
  `idEmploy` INT NOT NULL AUTO_INCREMENT,
  `EmployName` VARCHAR(45) NOT NULL,
  `EmploySalary` FLOAT NOT NULL,
  `idDepartament` INT NOT NULL,
  PRIMARY KEY (`idEmploy`),
  CONSTRAINT `idDepartment`
    FOREIGN KEY (`idDepartament`)
    REFERENCES `mydb1`.`Departments` (`idDepartments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idEmploy_UNIQUE` ON `mydb1`.`Employ` (`idEmploy` ASC);

CREATE INDEX `idDepartment_idx` ON `mydb1`.`Employ` (`idDepartament` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
